// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9NErHSvFU3ssRoPjpasJPLlHAma0YRE',
    appId: '1:1020202969338:web:40b8a111a9424611860143',
    messagingSenderId: '1020202969338',
    projectId: 'the-saviour-apps',
    authDomain: 'the-saviour-apps.firebaseapp.com',
    storageBucket: 'the-saviour-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4_X8Sd3S0AOX1cN8xMm3zNfsaOxeA10',
    appId: '1:1020202969338:android:28213f33856a25a2860143',
    messagingSenderId: '1020202969338',
    projectId: 'the-saviour-apps',
    storageBucket: 'the-saviour-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyN1mnW6zUlbfiwPcsaT7tlENzvOLshY',
    appId: '1:1020202969338:ios:d11626c5229e5be0860143',
    messagingSenderId: '1020202969338',
    projectId: 'the-saviour-apps',
    storageBucket: 'the-saviour-apps.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyN1mnW6zUlbfiwPcsaT7tlENzvOLshY',
    appId: '1:1020202969338:ios:d11626c5229e5be0860143',
    messagingSenderId: '1020202969338',
    projectId: 'the-saviour-apps',
    storageBucket: 'the-saviour-apps.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm9NErHSvFU3ssRoPjpasJPLlHAma0YRE',
    appId: '1:1020202969338:web:e2130c8761b05479860143',
    messagingSenderId: '1020202969338',
    projectId: 'the-saviour-apps',
    authDomain: 'the-saviour-apps.firebaseapp.com',
    storageBucket: 'the-saviour-apps.firebasestorage.app',
  );
}
